
import { Service, Package, Translation } from './types.ts';

export const TRANSLATIONS: Record<'en' | 'ar', Translation> = {
  en: {
    home: 'Home',
    services: 'Services',
    packages: 'Packages',
    about: 'About Us',
    contact: 'Contact',
    learnMore: 'LEARN MORE',
    bookNow: 'BOOK NOW',
    viewDetails: 'VIEW DETAILS',
    legacyTitle: 'THE REFLECTO LEGACY',
    legacySubtitle: 'PASSION MEETS PERFECTION',
    workshopTitle: 'THE WORKSHOP',
    smartBooking: 'REFLECTO SMART BOOKING',
    bookingSubtitle: 'Secure premium automotive protection for your vehicle. Select your car and desired services for a personalized quote.',
    selectCar: 'Select Car Brand',
    selectYear: 'Select Model Year',
    requestQuote: 'REQUEST A QUOTE',
    chatWhatsApp: 'Chat on WhatsApp',
  },
  ar: {
    home: 'الرئيسية',
    services: 'الخدمات',
    packages: 'الباقات',
    about: 'من نحن',
    contact: 'اتصل بنا',
    learnMore: 'إعرف المزيد',
    bookNow: 'احجز الآن',
    viewDetails: 'عرض التفاصيل',
    legacyTitle: 'إرث ريفليكتو',
    legacySubtitle: 'الشغف يلتقي بالإتقان',
    workshopTitle: 'الورشة',
    smartBooking: 'حجز ريفليكتو الذكي',
    bookingSubtitle: 'احصل على حماية متميزة لسيارتك. اختر نوع سيارتك والخدمات المطلوبة للحصول على عرض سعر مخصص.',
    selectCar: 'اختر ماركة السيارة',
    selectYear: 'اختر سنة الصنع',
    requestQuote: 'طلب عرض سعر',
    chatWhatsApp: 'تواصل عبر واتساب',
  },
};

export const SERVICES: Service[] = [
  {
    id: 'ppf',
    title: 'PAINT PROTECTION FILM',
    titleAr: 'حماية طلاء السيارات',
    description: 'Invisible shield against scratches, chips, and road debris. Self-healing technology.',
    descriptionAr: 'درع غير مرئي ضد الخدوش والرقائق وحطام الطريق. تكنولوجيا المعالجة الذاتية.',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800&auto=format&fit=crop',
    buttonText: 'VIEW PPF',
    buttonTextAr: 'عرض PPF',
  },
  {
    id: 'ceramic',
    title: 'NANO CERAMIC COATING',
    titleAr: 'طلاء النانو سيراميك',
    description: 'Extreme gloss, hydrophobic properties, and long-lasting protection.',
    descriptionAr: 'لمعان فائق، خصائص طاردة للماء، وحماية طويلة الأمد.',
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=800&auto=format&fit=crop',
    buttonText: 'VIEW CERAMIC',
    buttonTextAr: 'عرض السيراميك',
  },
  {
    id: 'tinting',
    title: 'THERMAL WINDOW TINTING',
    titleAr: 'التظليل الحراري للنوافذ',
    description: 'Superior heat rejection, UV protection, and enhanced privacy.',
    descriptionAr: 'رفض فائق للحرارة، حماية من الأشعة فوق البنفسجية، وخصوصية محسنة.',
    image: 'https://images.unsplash.com/photo-1542362567-b052cb1341f1?q=80&w=800&auto=format&fit=crop',
    buttonText: 'VIEW TINTING',
    buttonTextAr: 'عرض التظليل',
  },
  {
    id: 'detailing',
    title: 'PREMIUM DETAILING PACKAGES',
    titleAr: 'باقات التلميع الفاخرة',
    description: 'Meticulous interior and exterior cleaning, polishing, and restoration.',
    descriptionAr: 'تنظيف وتلميع وترميم داخلي وخارجي دقيق.',
    image: 'https://images.unsplash.com/photo-1601362840469-51e4d8d59085?q=80&w=800&auto=format&fit=crop',
    buttonText: 'VIEW DETAILING',
    buttonTextAr: 'عرض التلميع',
  },
];

export const PACKAGES: Package[] = [
  {
    name: 'BASIC',
    nameAr: 'أساسي',
    price: '$150',
    priceAr: '٥٦٠ ريال',
    features: [
      { label: 'Warranty', labelAr: 'الضمان', value: '3 years', valueAr: '٣ سنوات', included: true },
      { label: 'PPF Coverage', labelAr: 'تغطية PPF', value: 'Front Bumper', valueAr: 'مصد أمامي', included: true },
      { label: 'Ceramic Layers', labelAr: 'طبقات السيراميك', value: '1 Layer', valueAr: '١ طبقة', included: true },
      { label: 'Interior Detailing', labelAr: 'تلميع داخلي', value: 'Basic', valueAr: 'أساسي', included: true },
      { label: 'Thermal Tinting', labelAr: 'تظليل حراري', value: 'Side Windows', valueAr: 'النوافذ الجانبية', included: true },
    ],
  },
  {
    name: 'SILVER',
    nameAr: 'فضي',
    subtitle: '(BEST VALUE)',
    subtitleAr: '(القيمة الأفضل)',
    price: '$250',
    priceAr: '٩٣٠ ريال',
    isBestValue: true,
    features: [
      { label: 'Warranty', labelAr: 'الضمان', value: '5 years', valueAr: '٥ سنوات', included: true },
      { label: 'PPF Coverage', labelAr: 'تغطية PPF', value: 'Full Front', valueAr: 'كامل الأمام', included: true },
      { label: 'Ceramic Layers', labelAr: 'طبقات السيراميك', value: '2 Layers', valueAr: '٢ طبقة', included: true },
      { label: 'Interior Detailing', labelAr: 'تلميع داخلي', value: 'Standard', valueAr: 'قياسي', included: true },
      { label: 'Thermal Tinting', labelAr: 'تظليل حراري', value: 'All Windows', valueAr: 'كل النوافذ', included: true },
    ],
  },
  {
    name: 'DIAMOND',
    nameAr: 'ماسي',
    price: '$300',
    priceAr: '١١٢٠ ريال',
    features: [
      { label: 'Warranty', labelAr: 'الضمان', value: 'Lifetime', valueAr: 'مدى الحياة', included: true },
      { label: 'PPF Coverage', labelAr: 'تغطية PPF', value: 'Full Vehicle', valueAr: 'كامل السيارة', included: true },
      { label: 'Ceramic Layers', labelAr: 'طبقات السيراميك', value: '3 Layers', valueAr: '٣ طبقات', included: true },
      { label: 'Interior Detailing', labelAr: 'تلميع داخلي', value: 'Premium', valueAr: 'فاخر', included: true },
      { label: 'Thermal Tinting', labelAr: 'تظليل حراري', value: 'All + Sunroof', valueAr: 'كل النوافذ + فتحة سقف', included: true },
    ],
  },
];
